---
- name: Check ELRepo
  shell: rpm -q elrepo-release --qf '%{name}\n' warn=false
  register: check_elrepo
  changed_when: check_elrepo.stdout != 'elrepo-release'
  failed_when: false
  tags: packages

- name: Install ELRepo
  yum: name={{ elrepo_release_url }} state=present
  when: check_elrepo|changed
  tags: packages

- name: Import ELRepo GPG key
  rpm_key: key="{{ elrepo_repo_gpg_key_url }}" state=present
  tags: packages
